// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/06/2024, 21:29:33
const configMerger = require("/home/cheese/Development/ollo-v3/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/cheese/Development/ollo-v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cheese/Development/ollo-v3/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cheese/Development/ollo-v3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cheese/Development/ollo-v3/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cheese/Development/ollo-v3/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cheese/Development/ollo-v3/plugins/**/*.{js,ts,mjs}","/home/cheese/Development/ollo-v3/composables/**/*.{js,ts,mjs}","/home/cheese/Development/ollo-v3/utils/**/*.{js,ts,mjs}","/home/cheese/Development/ollo-v3/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/cheese/Development/ollo-v3/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/cheese/Development/ollo-v3/app.config.{js,ts,mjs}"] }));

module.exports = config
